[pytest]
asyncio_mode = auto
markers =
    integration: integration tests that require live services
pythonpath = .
testpaths = tests

env =
    TITLE=AI Agents
    DEBUG=true

    BASE_URL=http://localhost:8000
    SECRET_KEY=q1uxnrFsLRR4lXkoIj1FyODPr7tSF771
    REDIS_DSN=redis://localhost:6379/0
    CORS_ORIGINS=["127.0.0.1", "localhost"]
    SENTRY_DSN=

    DB__HOST=localhost
    DB__PORT=5432
    DB__USER=postgres
    DB__PASSWORD=12345678
    DB__NAME=yafs_test
