import { Global, Module } from '@nestjs/common'

import { ApiKeyGuard } from '../apps/api/auth/api-key.guard.js'
import { McpAuthGuard } from '../apps/api/auth/mcp-auth.guard.js'

import { AgentsInternalAuthGuard } from './agents-internal-auth.guard.js'

/**
 * Globally exported auth guards.
 *
 * These three guards are used both by the REST API controllers (ApiModule) and
 * by the MCP transport controllers generated by @rekog/mcp-nest. Because the
 * library's McpNestModule creates its own DI scope for the transport
 * controllers, any guard passed via McpModule.forRoot({ guards: [...] }) must
 * have all of its own dependencies resolvable from the global scope. Making
 * ApiKeyGuard and friends global here satisfies that requirement without
 * introducing circular module dependencies.
 */
@Global()
@Module({
  providers: [AgentsInternalAuthGuard, ApiKeyGuard, McpAuthGuard],
  exports: [AgentsInternalAuthGuard, ApiKeyGuard, McpAuthGuard],
})
export class AuthModule {}
