import { describe, expect, it } from 'vitest'
import { strToU8, zipSync } from 'fflate'

import { buildConfluenceImportPlan } from '../../src/server/page-import/confluence/confluence-plan'

const PAGE = (title: string, body: string) =>
  `<html><head><title>${title} - Мой Confluence</title></head><body>
   <div id="breadcrumbs">Хлебные крошки</div>
   <div id="main-content"><h1>${title}</h1><p>${body}</p></div>
   <div id="footer">Generated by Confluence</div></body></html>`

describe('buildConfluenceImportPlan', () => {
  it('imports content html pages, strips chrome, skips index.html with a note', () => {
    const plan = buildConfluenceImportPlan(
      zipSync({
        'SPACE/index.html': strToU8('<html><body>toc</body></html>'),
        'SPACE/Page-One.html': strToU8(PAGE('Первая', 'тело')),
        'SPACE/attachments/123/pic.png': new Uint8Array([1]),
      }),
    )
    const all = JSON.stringify(plan.roots)
    expect(all).toContain('Первая')
    expect(all).not.toContain('Хлебные крошки')
    expect(all).not.toContain('Generated by Confluence')
    expect(plan.assets.size).toBe(1)
    expect(plan.warnings.some((w) => w.includes('index.html'))).toBe(true)
    expect(plan.warnings.some((w) => w.includes('Confluence'))).toBe(true) // limitations note
  })
})
