import { Readable } from 'node:stream'

import { afterAll, beforeEach, describe, expect, it } from 'vitest'
import { strToU8, zipSync } from 'fflate'
import { prisma } from '@repo/db'

import { domain } from '@/lib/domain'
import {
  processImportJob,
  streamToBuffer,
  type ImportJobContext,
} from '@/server/jobs/process-import-job'

const EMAIL_SUFFIX = '+notion-import-test@anynote.dev'

const ID_PAGE = 'a1b2c3d4e5f60718293a4b5c6d7e8f90'
const ID_ROW = 'b2c3d4e5f60718293a4b5c6d7e8f90a1'

// NOTE: the same ID_PAGE on the .md and the .csv makes the bare-id alias
// last-write-wins (csv); links below use the row's unique ID_ROW + raw paths.
const NOTION_ZIP = () =>
  zipSync({
    [`Проект ${ID_PAGE}.md`]: strToU8(
      `# Проект\n\nСм. [строку](%D0%91%D0%B0%D0%B7%D0%B0%20${ID_PAGE}/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0%20%D0%90%20${ID_ROW}.md) и [внешн](https://www.notion.so/ws/Other-${ID_ROW}).\n`,
    ),
    [`База ${ID_PAGE}.csv`]: strToU8('Name,Status\nЗадача А,Open\nЗадача Б,Done\nЗадача В,Open\n'),
    [`База ${ID_PAGE}/Задача А ${ID_ROW}.md`]: strToU8('# Задача А\n\nтело А'),
  })

const CONFLUENCE_PAGE = (title: string, body: string) =>
  `<html><head><title>${title} - Мой Confluence</title></head><body>
   <div id="breadcrumbs">Хлебные крошки</div>
   <div id="main-content"><h1>${title}</h1><p>${body}</p></div>
   <div id="footer">Generated by Confluence</div></body></html>`

const CONFLUENCE_ZIP = () =>
  zipSync({
    'SPACE/index.html': strToU8('<html><body>toc</body></html>'),
    'SPACE/Page-One.html': strToU8(CONFLUENCE_PAGE('Первая', 'тело страницы')),
  })

function makeFakeStorage(initial: Record<string, Buffer> = {}) {
  const store = new Map<string, Buffer>(Object.entries(initial))
  return {
    store,
    async get(key: string): Promise<Readable> {
      const buf = store.get(key)
      if (!buf) throw new Error(`missing ${key}`)
      return Readable.from([buf])
    },
    async put(key: string, body: Readable | Buffer): Promise<void> {
      store.set(key, Buffer.isBuffer(body) ? body : await streamToBuffer(body))
    },
  }
}

async function cleanFixtures() {
  const where = { workspace: { createdBy: { email: { contains: EMAIL_SUFFIX } } } }
  const wsWhere = { createdBy: { email: { contains: EMAIL_SUFFIX } } }
  const wsIds = (await prisma.workspace.findMany({ where: wsWhere, select: { id: true } })).map(
    (w) => w.id,
  )
  await prisma.importJob.deleteMany({ where })
  await prisma.databaseCellValue.deleteMany({ where: { row: { source: { workspace: wsWhere } } } })
  await prisma.databaseRow.deleteMany({ where: { source: { workspace: wsWhere } } })
  await prisma.databaseProperty.deleteMany({ where: { source: { workspace: wsWhere } } })
  await prisma.databaseView.deleteMany({ where: { source: { workspace: wsWhere } } })
  await prisma.databaseSource.deleteMany({ where: { workspace: wsWhere } })
  await prisma.pageFile.deleteMany({ where: { page: where } })
  if (wsIds.length > 0) {
    await prisma.outboxEvent.deleteMany({ where: { workspaceId: { in: wsIds } } })
  }
  await prisma.page.deleteMany({ where })
  await prisma.file.deleteMany({ where: { user: { email: { contains: EMAIL_SUFFIX } } } })
  await prisma.collection.deleteMany({ where })
  await prisma.workspaceMember.deleteMany({ where })
  await prisma.workspaceLimit.deleteMany({ where })
  await prisma.workspace.deleteMany({ where: wsWhere })
  await prisma.user.deleteMany({ where: { email: { contains: EMAIL_SUFFIX } } })
}

async function seed(zipBytes: Uint8Array, source: 'NOTION' | 'CONFLUENCE') {
  const user = await prisma.user.create({
    data: {
      email: `owner${EMAIL_SUFFIX}`,
      emailVerified: true,
      name: 'owner',
      firstName: 'O',
      lastName: 'T',
    },
  })
  const ws = await prisma.workspace.create({ data: { name: 'NotionWS', createdById: user.id } })
  await prisma.workspaceMember.create({
    data: { workspaceId: ws.id, userId: user.id, role: 'OWNER' },
  })
  await prisma.collection.create({ data: { workspaceId: ws.id, kind: 'TEAM' } })
  await prisma.workspaceLimit.create({
    data: { workspaceId: ws.id, maxMembers: 100, maxFileBytes: 10n ** 12n, syncedAt: new Date() },
  })
  const sourceFile = await prisma.file.create({
    data: {
      userId: user.id,
      workspaceId: ws.id,
      name: 'export.zip',
      ext: 'zip',
      fileSize: BigInt(zipBytes.byteLength),
      mimeType: 'application/zip',
      hash: 'test-source-hash',
      path: 'test/source.zip',
      status: 'ACTIVE',
      isPublic: false,
    },
  })
  const job = await prisma.importJob.create({
    data: {
      workspaceId: ws.id,
      userId: user.id,
      format: 'ZIP',
      source,
      options: { location: 'team', parentId: null },
      artifacts: { create: { fileId: sourceFile.id, kind: 'SOURCE' } },
    },
  })
  const storage = makeFakeStorage({ 'test/source.zip': Buffer.from(zipBytes) })
  const ctx: ImportJobContext = { prisma, storage, pages: domain.pages, database: domain.database }
  return { user, ws, job, storage, ctx }
}

describe('processImportJob — source dispatch', () => {
  beforeEach(cleanFixtures)
  afterAll(cleanFixtures)

  it('imports a Notion export: cleaned pages, real database, alias-resolved links, report', async () => {
    const { user, ws, job, storage, ctx } = await seed(NOTION_ZIP(), 'NOTION')
    await processImportJob(ctx, job.id)

    const done = await prisma.importJob.findUniqueOrThrow({ where: { id: job.id } })
    expect(done.status).toBe('DONE')
    expect(done.total).toBe(5) // Проект + db page + 3 rows
    expect(done.processed).toBe(5)

    // Cleaned titles: the 32-hex Notion ids never reach page titles.
    const project = await prisma.page.findFirstOrThrow({
      where: { workspaceId: ws.id, title: 'Проект' },
    })
    const titles = await prisma.page.findMany({
      where: { workspaceId: ws.id },
      select: { title: true },
    })
    expect(
      titles.some((p) => (p.title ?? '').includes(ID_PAGE) || (p.title ?? '').includes(ID_ROW)),
    ).toBe(false)

    // Materialized DATABASE page: inferred SELECT property + 3 rows.
    const dbPage = await prisma.page.findFirstOrThrow({
      where: { workspaceId: ws.id, title: 'База', type: 'DATABASE' },
    })
    const props = await domain.database.listProperties(user.id, dbPage.id)
    const status = props.find((p) => p.name === 'Status')
    expect(status?.type).toBe('SELECT')
    const { rows } = await domain.database.listRows(user.id, { pageId: dbPage.id, limit: 100 })
    expect(rows).toHaveLength(3)

    // The row doc became the item page body.
    const rowA = rows.find((r) => r.title === 'Задача А')
    expect(rowA).toBeDefined()
    const itemA = await prisma.page.findUniqueOrThrow({ where: { id: rowA!.pageId } })
    expect(JSON.stringify(itemA.content)).toContain('тело А')

    // BOTH links (encoded relative row path + notion.so URL) → the item page.
    const content = JSON.stringify(project.content)
    const hits = content.split(`/pages/${rowA!.pageId}`).length - 1
    expect(hits).toBe(2)
    expect(content).not.toContain('notion.so')

    const result = done.result as { rootPageIds: string[]; warnings: string[] }
    expect(result.warnings).toContain('Комментарии, права доступа и история Notion не переносятся')
    expect(result.rootPageIds).toEqual([project.id, dbPage.id])

    // REPORT artifact: owner-only file (workspaceId NULL) + rendered journal.
    const report = await prisma.importArtifact.findFirstOrThrow({
      where: { jobId: job.id, kind: 'REPORT' },
      include: { file: true },
    })
    expect(report.file.workspaceId).toBeNull()
    expect(report.file.isPublic).toBe(false)
    const text = storage.store.get(`imports/${job.id}-report.txt`)?.toString('utf-8') ?? ''
    expect(text).toContain('Источник: NOTION')
    expect(text).toContain('Страница «Проект»')
    expect(text).toContain('База данных «База»')
  })

  it('is idempotent on re-run including database rows; one report artifact remains', async () => {
    const { user, ws, job, ctx } = await seed(NOTION_ZIP(), 'NOTION')
    await processImportJob(ctx, job.id)
    const pagesAfterFirst = await prisma.page.count({ where: { workspaceId: ws.id } })

    await prisma.importJob.update({
      where: { id: job.id },
      data: { status: 'QUEUED', heartbeatAt: null },
    })
    await processImportJob(ctx, job.id)

    expect(await prisma.page.count({ where: { workspaceId: ws.id } })).toBe(pagesAfterFirst)
    const dbPage = await prisma.page.findFirstOrThrow({
      where: { workspaceId: ws.id, title: 'База', type: 'DATABASE' },
    })
    const props = await domain.database.listProperties(user.id, dbPage.id)
    expect(props).toHaveLength(1) // Status only, no duplicate from the re-run
    const { rows } = await domain.database.listRows(user.id, { pageId: dbPage.id, limit: 100 })
    expect(rows).toHaveLength(3)

    const reports = await prisma.importArtifact.findMany({
      where: { jobId: job.id, kind: 'REPORT' },
    })
    expect(reports).toHaveLength(1)
    const done = await prisma.importJob.findUniqueOrThrow({ where: { id: job.id } })
    expect(done.status).toBe('DONE')
  })

  it('imports a Confluence export: stripped chrome + limitations note in the journal', async () => {
    const { ws, job, storage, ctx } = await seed(CONFLUENCE_ZIP(), 'CONFLUENCE')
    await processImportJob(ctx, job.id)

    const done = await prisma.importJob.findUniqueOrThrow({ where: { id: job.id } })
    expect(done.status).toBe('DONE')

    const page = await prisma.page.findFirstOrThrow({
      where: { workspaceId: ws.id, title: 'Первая' },
    })
    expect(JSON.stringify(page.content)).toContain('тело страницы')
    expect(JSON.stringify(page.content)).not.toContain('Хлебные крошки')

    const text = storage.store.get(`imports/${job.id}-report.txt`)?.toString('utf-8') ?? ''
    expect(text).toContain('Источник: CONFLUENCE')
    expect(text).toContain('Confluence: права, история, комментарии и макросы не переносятся')
  })
})
